<a href="https://colab.research.google.com/github/thilankam/PyTorch_Tutorials/blob/main/Pytorch_practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np


Tensors

TORCH.TENSOR
A torch.Tensor is a multi-dimensional matrix containing elements of a single data type.

torch.Tensor is an alias for the default tensor type (torch.FloatTensor).

https://pytorch.org/docs/stable/tensors.html#id5


In [2]:
import torch
import numpy as np

torch.__version__

'1.13.1+cu116'

In [3]:
torch.tensor([[1., -1.], [1., -1.]])
torch.tensor(np.array([[1, 2, 3], [4, 5, 6]]))

tensor([[1, 2, 3],
        [4, 5, 6]])

torch.tensor() always copies data. If you have a Tensor data and just want to change its requires_grad flag, use requires_grad_() or detach() to avoid a copy. If you have a numpy array and want to avoid a copy, use torch.as_tensor().

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]], device='cuda:0', dtype=torch.float64)

In [4]:
x = torch.randn(5, requires_grad=True)
y = x.pow(2)
print(x.equal(y.grad_fn._saved_self))  # True
print(x is y.grad_fn._saved_self)  # True

True
True


In [5]:
x
y

tensor([8.7072e-01, 6.8402e+00, 2.3037e+00, 4.6733e-03, 2.9845e-01],
       grad_fn=<PowBackward0>)

In [6]:
x = torch.tensor([[1]])
x
x.item()

1

In [7]:

x = torch.tensor(2.5)
x
x.item()

2.5

In [8]:
data = [[1,2],[3,4]]
x_data = torch.tensor(data)

In [9]:
x_data

tensor([[1, 2],
        [3, 4]])

In [10]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)

In [11]:
x_np

tensor([[1, 2],
        [3, 4]])

In [12]:
x_ones = torch.ones_like(x_data)
x_ones
# print(f"Ones Tensor: \n {x_ones} \n")

tensor([[1, 1],
        [1, 1]])

In [13]:
x_rand = torch.rand_like(x_data, dtype=torch.float)
x_rand

tensor([[0.7716, 0.7019],
        [0.5601, 0.0760]])

In [14]:
shape = (2,3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.0151, 0.4087, 0.0961],
        [0.7572, 0.9277, 0.6054]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


Examples from 
https://pytorch.org/tutorials/beginner/basics/tensorqs_tutorial.html

In [15]:
tensor = torch.rand(3,4)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


In [16]:
tensor = torch.ones(4,4)
tensor

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [17]:
tensor[0]

tensor([1., 1., 1., 1.])

In [18]:
print(f"First row: {tensor[0]}")

First row: tensor([1., 1., 1., 1.])


In [33]:
print(f"First Column: {tensor[:,0]}")

First Column: tensor([1., 1., 1., 1.])


In [34]:
print(f"Last Column:{tensor[...,-1]} ")

Last Column:tensor([1., 1., 1., 1.]) 


In [35]:
tensor[:,1] = 0
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [38]:
t1 = torch.cat([tensor,tensor], dim=1)
t1

tensor([[1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1.]])