<a href="https://colab.research.google.com/github/thilankam/PyTorch_Tutorials/blob/main/PyTorch_Tensors_Tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Tensors
This tutorial is based on the Tensors. A tensor is a generalization of vectors and matrices and is easily understood as multidimentional array. 
Tensors are a type of data structures used in liner algebra (similar to vectors and matrices). 
We can use to calculate arithmetic operations tensors.

In [ ]:
import torch
torch.__version__
import numpy as np
lst = [10,20,30,40,50,60,70,80]
# creating a numpy array using the list
arr = np.array(lst)
arr 
# checking the data type
arr.dtype

dtype('int64')

Now we will convert from Numpy to Tensor

In [ ]:
tensors = torch.from_numpy(arr)
tensors

tensor([10, 20, 30, 40, 50, 60, 70, 80])

We can do indexing similar to how we do it in numpy.

In [ ]:
tensors[:4]
#tensors[1:3]


tensor([10, 20, 30, 40])

In [ ]:
tensors[2:6]

tensor([30, 40, 50, 60])

In [ ]:
tensors[0]

tensor(10)

One of the disadvantage of from_numpy is that both tensor and array uses the same memory location. If we change a one element, it will change in both array and the tensor.

In [23]:
tensors[3] = 75
tensors
arr

array([10, 20, 30, 75, 50, 60, 70, 80])

To avoid sharing the same memory location, instead of using "from_numpy" we can use the "torch.tensor" as shown below.

In [25]:
tensor_arr = torch.tensor(arr)
tensor_arr

tensor([10, 20, 30, 75, 50, 60, 70, 80])

now we will change the 3rd element to 99

In [26]:
tensor_arr[3] = 99
tensor_arr

tensor([10, 20, 30, 99, 50, 60, 70, 80])

creating a tensor with zeros

In [28]:
torch.zeros(3,4,dtype=torch.float64)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]], dtype=torch.float64)

creating a tensor with ones

In [30]:

torch.ones(3,4,dtype=torch.float64)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]], dtype=torch.float64)

In [32]:
t = torch.tensor(np.arange(0,15).reshape(5,3))
t

tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14]])

accessing the first two columns with all the rows

In [33]:
t[:,0:2]

tensor([[ 0,  1],
        [ 3,  4],
        [ 6,  7],
        [ 9, 10],
        [12, 13]])

now we will perform some basic mathematical operations such as addition and substractions with tensors.

Addition Operation

In [35]:
t1 = torch.tensor([1,2,3], dtype=torch.float64)
t2 = torch.tensor([4,5,6], dtype=torch.float64)
print(t1 + t2)

tensor([5., 7., 9.], dtype=torch.float64)


In [37]:
torch.add(t1,t2)

tensor([5., 7., 9.], dtype=torch.float64)

Substration Operation

In [38]:
print(t1 - t2)

tensor([-3., -3., -3.], dtype=torch.float64)


In [39]:
torch.sub(t1,t2)

tensor([-3., -3., -3.], dtype=torch.float64)

now we will add two tensors and assign the results to another tensor 

In [41]:
t3 = torch.zeros(3,dtype=torch.float64)
t3

tensor([0., 0., 0.], dtype=torch.float64)

In [42]:
torch.add(t1,t2, out=t3)
t3

tensor([5., 7., 9.], dtype=torch.float64)

Multiplication operations: Dot Product

In [43]:
# using the mul() 
t1.mul(t2)

tensor([ 4., 10., 18.], dtype=torch.float64)

In [44]:
# using the dot() for dot product
t1.dot(t2)

tensor(32., dtype=torch.float64)

Matrix Multiplication Example


In [50]:
m1 = torch.tensor([[2,3,4], [5,6,7]], dtype=torch.float64)
m2 = torch.tensor([[5,6],[7,8],[10,11]],dtype=torch.float64)

In [51]:
# matrix multiplication using the matmul()
torch.matmul(m1,m2)

tensor([[ 71.,  80.],
        [137., 155.]], dtype=torch.float64)

In [52]:
# same matrix multiplication can be done using the mm()
torch.mm(m1,m2)

tensor([[ 71.,  80.],
        [137., 155.]], dtype=torch.float64)

In [53]:
# same matrix multiplication can be done using "@"
m1@m2

tensor([[ 71.,  80.],
        [137., 155.]], dtype=torch.float64)