<a href="https://colab.research.google.com/github/thilankam/PyTorch_Tutorials/blob/main/Pytorch_tutorial_and_examples.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Scalar

In [1]:
import torch
torch.__version__

'1.12.1+cu113'

In [7]:
#scalar
s1 = torch.tensor(10)
s1
s1.shape
s1.dtype
s1.ndim

0

In [8]:
# get the tensor information 
s1.item()

10

Vector

A vector is a single dimension tensor but can contain many numbers.



In [13]:
v1 = torch.tensor([2,4])
v1
v1.dtype
v1.ndim
v1.shape

torch.Size([2])

Another important concept for tensors is their shape attribute. The shape tells you how the elements inside them are arranged.

In [16]:
# scalr 
s1.shape

# vector, 
# check the shape
v1.shape


torch.Size([2])

In [19]:
v2 = torch.tensor([4,6,8,10,12])
v2
v2.shape

torch.Size([5])

Matrices


In [23]:
M1 = torch.tensor(([4,5],[7,8]))
M1
M1.ndim
M1.shape

torch.Size([2, 2])

Tensor

In [24]:
T1 = torch.tensor([[[3,4,5],[6,7,8],[9,10,11]]])
T1

tensor([[[ 3,  4,  5],
         [ 6,  7,  8],
         [ 9, 10, 11]]])

In [25]:
# dimentions
T1.ndim

3

In [26]:
# shape
T1.shape

torch.Size([1, 3, 3])

create a tensor of random numbers.

In [28]:
# Create a random tensor of size (3, 4)
T1 = torch.rand(size=(3,4))
T1,T1.dtype

(tensor([[0.6294, 0.0239, 0.3218, 0.2394],
         [0.7790, 0.0583, 0.4680, 0.6851],
         [0.9535, 0.5557, 0.6354, 0.7756]]), torch.float32)

In [31]:
# Create a random tensor of size (224, 224, 3)
Random_Image_Size_Tensor = torch.rand(size=(224,224,3))
Random_Image_Size_Tensor.shape, Random_Image_Size_Tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [34]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3,4))
zeros, zeros.shape,zeros.ndim

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]), torch.Size([3, 4]), 2)

In [36]:
# Create a tensor of all ones
ones = torch.ones(size=(3,4))
ones, ones.dtype, ones.shape, ones.ndim

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]), torch.float32, torch.Size([3, 4]), 2)