<a href="https://colab.research.google.com/github/thilankam/PyTorch_Tutorials/blob/main/Pytorch_tutorial_and_examples.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Scalar

In [1]:
import torch
torch.__version__

'1.12.1+cu113'

In [2]:
#scalar
s1 = torch.tensor(10)
s1
s1.shape
s1.dtype
s1.ndim

0

In [ ]:
# get the tensor information 
s1.item()

10

Vector

A vector is a single dimension tensor but can contain many numbers.



In [ ]:
v1 = torch.tensor([2,4])
v1
v1.dtype
v1.ndim
v1.shape

torch.Size([2])

Another important concept for tensors is their shape attribute. The shape tells you how the elements inside them are arranged.

In [ ]:
# scalr 
s1.shape

# vector, 
# check the shape
v1.shape


torch.Size([2])

In [ ]:
v2 = torch.tensor([4,6,8,10,12])
v2
v2.shape

torch.Size([5])

Matrices


In [ ]:
M1 = torch.tensor(([4,5],[7,8]))
M1
M1.ndim
M1.shape

torch.Size([2, 2])

Tensor

In [ ]:
T1 = torch.tensor([[[3,4,5],[6,7,8],[9,10,11]]])
T1

tensor([[[ 3,  4,  5],
         [ 6,  7,  8],
         [ 9, 10, 11]]])

In [ ]:
# dimentions
T1.ndim

3

In [ ]:
# shape
T1.shape

torch.Size([1, 3, 3])

create a tensor of random numbers.

In [ ]:
# Create a random tensor of size (3, 4)
T1 = torch.rand(size=(3,4))
T1,T1.dtype

(tensor([[0.6294, 0.0239, 0.3218, 0.2394],
         [0.7790, 0.0583, 0.4680, 0.6851],
         [0.9535, 0.5557, 0.6354, 0.7756]]), torch.float32)

In [ ]:
# Create a random tensor of size (224, 224, 3)
Random_Image_Size_Tensor = torch.rand(size=(224,224,3))
Random_Image_Size_Tensor.shape, Random_Image_Size_Tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [ ]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3,4))
zeros, zeros.shape,zeros.ndim

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]), torch.Size([3, 4]), 2)

In [ ]:
# Create a tensor of all ones
ones = torch.ones(size=(3,4))
ones, ones.dtype, ones.shape, ones.ndim

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]), torch.float32, torch.Size([3, 4]), 2)

Creeating a range of numbers


In [ ]:
zero_to_ten = torch.arange(0,10,1)
zero_to_ten
zero_to_ten.ndim
zero_to_ten.shape

torch.Size([10])

tensor of all zeros with the same shape as a previous tensor.

In [ ]:
ten_zeros = torch.zeros_like(zero_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

 Default datatype for tensors is float32

In [ ]:
float_32_tensor = torch.tensor([2.0,3.0,4.0],
                               dtype= None,
                               device= None,
                               requires_grad= False
                               )

float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device, float_32_tensor.ndim



(torch.Size([3]), torch.float32, device(type='cpu'), 1)

In [6]:
T3 = torch.tensor([1,2,3])
T3
T3*3
T3 +10

tensor([11, 12, 13])

In [7]:
T3 - 10


tensor([-9, -8, -7])

In [8]:
torch.multiply(T3,20)

tensor([20, 40, 60])

In [10]:
print(T3, '*' , T3)
T3*T3

tensor([1, 2, 3]) * tensor([1, 2, 3])


tensor([1, 4, 9])

In [13]:
T4 = torch.tensor([1,2,3])
T4.shape

torch.Size([3])

In [16]:
T3 * T3
T3.matmul(T3)
T3 @ T3

tensor(14)

In [19]:
T_A = torch.tensor([[1,2],[3,4],[5,6]],dtype=torch.float32)
T_B = torch.tensor([[7,10],[8,11],[9,12]],dtype=torch.float32)
T_A.shape,T_A.ndim
T_B.shape, T_B.ndim


(torch.Size([3, 2]), 2)

In [20]:
T_B.T

tensor([[ 7.,  8.,  9.],
        [10., 11., 12.]])

In [23]:
# Tensor Multiplication, Tensor Matrix multiplication
output = torch.matmul(T_A,T_B.T)
output.shape

torch.Size([3, 3])

In [24]:
torch.mm(T_A,T_B.T)

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

In [25]:
# Since the linear layer starts with a random weights matrix, let's make it reproducible (more on this later)
torch.manual_seed(42)
# This uses matrix mutliplcation
linear = torch.nn.Linear(in_features=2, # in_features = matches inner dimension of input 
                         out_features=6) # out_features = describes outer value 
x = T_A
output = linear(x)
print(f"Input shape: {x.shape}\n")
print(f"Output:\n{output}\n\nOutput shape: {output.shape}")

Input shape: torch.Size([3, 2])

Output:
tensor([[2.2368, 1.2292, 0.4714, 0.3864, 0.1309, 0.9838],
        [4.4919, 2.1970, 0.4469, 0.5285, 0.3401, 2.4777],
        [6.7469, 3.1648, 0.4224, 0.6705, 0.5493, 3.9716]],
       grad_fn=<AddmmBackward0>)

Output shape: torch.Size([3, 6])


In [32]:
x = torch.arange(0,100,10)
x.max()
x.type(torch.float32).mean()

tensor(45.)

find the index of a tensor where the max or minimum occurs with torch.argmax() and torch.argmin() respectively.



In [34]:
x.argmax()
x.argmin()

tensor(0)

In [36]:
x1 = torch.arange(1,10).reshape(1,3,3)
x1.shape, x1

(torch.Size([1, 3, 3]), tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]))

Indexing values goes outer dimension -> inner dimension (check out the square brackets).

In [37]:
x1[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [38]:
print(f"First square bracket:\n{x1[0]}") 

First square bracket:
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])


In [39]:
print(f"second square bracket:\n{x1[0][0]}") 

second square bracket:
tensor([1, 2, 3])


In [40]:
print(f"Third square bracket: {x1[0][0][0]}")

Third square bracket: 1


In [41]:
# Get all values of 0th dimension and the 0 index of 1st dimension
x1[:, 0]

tensor([[1, 2, 3]])

In [42]:
# Get all values of 0th & 1st dimensions but only index 1 of 2nd dimension
x1[:,:,1]

tensor([[2, 5, 8]])

In [43]:
# Get all values of the 0 dimension but only the 1 index value of the 1st and 2nd dimension
x1[:,1,1]

tensor([5])

In [45]:
# Get index 0 of 0th and 1st dimension and all values of 2nd dimension 
x1[0, 0, :] # same as x[0][0]

tensor([1, 2, 3])

In [46]:
import numpy as np
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [47]:
# Change the array, keep the tensor
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [48]:
# Tensor to NumPy array
tensor = torch.ones(7) # create a tensor of ones with dtype=float32
numpy_tensor = tensor.numpy() # will be dtype=float32 unless changed
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [49]:
# Change the tensor, keep the array the same
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [50]:
import torch

# Create two random tensors
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(f"Tensor A:\n{random_tensor_A}\n")
print(f"Tensor B:\n{random_tensor_B}\n")
print(f"Does Tensor A equal Tensor B? (anywhere)")
random_tensor_A == random_tensor_B

Tensor A:
tensor([[0.2666, 0.6274, 0.2696, 0.4414],
        [0.2969, 0.8317, 0.1053, 0.2695],
        [0.3588, 0.1994, 0.5472, 0.0062]])

Tensor B:
tensor([[0.9516, 0.0753, 0.8860, 0.5832],
        [0.3376, 0.8090, 0.5779, 0.9040],
        [0.5547, 0.3423, 0.6343, 0.3644]])

Does Tensor A equal Tensor B? (anywhere)


tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

In [51]:

import random

# # Set the random seed
RANDOM_SEED=42 # try changing this to different values and see what happens to the numbers below
torch.manual_seed(seed=RANDOM_SEED) 
random_tensor_C = torch.rand(3, 4)

# Have to reset the seed every time a new rand() is called 
# Without this, tensor_D would be different to tensor_C 
torch.random.manual_seed(seed=RANDOM_SEED) # try commenting this line out and seeing what happens
random_tensor_D = torch.rand(3, 4)

print(f"Tensor C:\n{random_tensor_C}\n")
print(f"Tensor D:\n{random_tensor_D}\n")
print(f"Does Tensor C equal Tensor D? (anywhere)")
random_tensor_C == random_tensor_D

Tensor C:
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

Tensor D:
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

Does Tensor C equal Tensor D? (anywhere)


tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

In [53]:
# Set device type
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cpu'

In [54]:
# Create tensor (default on CPU)
tensor = torch.tensor([1, 2, 3])

# Tensor not on GPU
print(tensor, tensor.device)

# Move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3]) cpu


tensor([1, 2, 3])

In [55]:
# Instead, copy the tensor back to cpu
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])

# Reference 

https://www.learnpytorch.io/00_pytorch_fundamentals/

In [64]:
T2 = torch.tensor([[[2,3,5],[4,5,9],[10,11,12]]])
T2 , T2.shape

(tensor([[[ 2,  3,  5],
          [ 4,  5,  9],
          [10, 11, 12]]]), torch.Size([1, 3, 3]))

In [66]:
T3 = torch.tensor([[[23,34,45],
                    [55,66,77],
                    [88,99,111]]])
T3, T3.ndim, T3.shape

(tensor([[[ 23,  34,  45],
          [ 55,  66,  77],
          [ 88,  99, 111]]]), 3, torch.Size([1, 3, 3]))

In [67]:
T3[0]

tensor([[ 23,  34,  45],
        [ 55,  66,  77],
        [ 88,  99, 111]])

In [70]:
T3[0][1]

tensor([55, 66, 77])

In [71]:
T3[0][0]

tensor([23, 34, 45])

In [74]:
T3[0][2]

tensor([ 88,  99, 111])

In [76]:
T4 = torch.tensor([[[[1,2,3],
                     [12,23,34],
                     [43,54,65],
                     [90,87,65],
                     [123,321,456]]]])
T4, T4.ndim, T4.shape

(tensor([[[[  1,   2,   3],
           [ 12,  23,  34],
           [ 43,  54,  65],
           [ 90,  87,  65],
           [123, 321, 456]]]]), 4, torch.Size([1, 1, 5, 3]))

In [77]:
T4[0]

tensor([[[  1,   2,   3],
         [ 12,  23,  34],
         [ 43,  54,  65],
         [ 90,  87,  65],
         [123, 321, 456]]])

In [81]:
T4[0][0][0]

tensor([1, 2, 3])

In [82]:
T4[0][0][1]

tensor([12, 23, 34])

In [83]:
T4[0][0][2]

tensor([43, 54, 65])

In [84]:
T4[0][0][3]

tensor([90, 87, 65])

In [85]:
T4[0][0][4]

tensor([123, 321, 456])

In [87]:
T4[0][0][:,0]

tensor([  1,  12,  43,  90, 123])

In [88]:
T4[0][0][:,1]

tensor([  2,  23,  54,  87, 321])

In [89]:
T4[0][0][:,2]

tensor([  3,  34,  65,  65, 456])

In [91]:
T4[0][0][0,:]

tensor([1, 2, 3])

In [92]:
T4[0][0][1,:]

tensor([12, 23, 34])

In [93]:
T4[0][0][2,:]

tensor([43, 54, 65])

In [94]:
T4[0][0][3,:]

tensor([90, 87, 65])

In [95]:
T4[0][0][4,:]

tensor([123, 321, 456])

In [105]:
T4[0][0][4,2]

tensor(456)

In [108]:
T4[0][0][4,1]

tensor(321)

In [113]:
T4[0][0][1,2]

tensor(34)