<a href="https://colab.research.google.com/github/thilankam/PyTorch_Tutorials/blob/main/Pytorch_practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np


Tensors

TORCH.TENSOR
A torch.Tensor is a multi-dimensional matrix containing elements of a single data type.

torch.Tensor is an alias for the default tensor type (torch.FloatTensor).

https://pytorch.org/docs/stable/tensors.html#id5


In [3]:
import torch
import numpy as np

torch.__version__

'1.13.1+cu116'

In [4]:
torch.tensor([[1., -1.], [1., -1.]])
torch.tensor(np.array([[1, 2, 3], [4, 5, 6]]))

tensor([[1, 2, 3],
        [4, 5, 6]])

torch.tensor() always copies data. If you have a Tensor data and just want to change its requires_grad flag, use requires_grad_() or detach() to avoid a copy. If you have a numpy array and want to avoid a copy, use torch.as_tensor().

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]], device='cuda:0', dtype=torch.float64)

In [5]:
x = torch.randn(5, requires_grad=True)
y = x.pow(2)
print(x.equal(y.grad_fn._saved_self))  # True
print(x is y.grad_fn._saved_self)  # True

True
True


In [6]:
x
y

tensor([0.6691, 0.0136, 1.0011, 3.6035, 1.1928], grad_fn=<PowBackward0>)

In [9]:
x = torch.tensor([[1]])
x
x.item()

1

In [10]:

x = torch.tensor(2.5)
x
x.item()

2.5

In [11]:
data = [[1,2],[3,4]]
x_data = torch.tensor(data)

In [12]:
x_data

tensor([[1, 2],
        [3, 4]])

In [14]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)

In [15]:
x_np

tensor([[1, 2],
        [3, 4]])

In [20]:
x_ones = torch.ones_like(x_data)
x_ones
# print(f"Ones Tensor: \n {x_ones} \n")

tensor([[1, 1],
        [1, 1]])

In [24]:
x_rand = torch.rand_like(x_data, dtype=torch.float)
x_rand

tensor([[0.6495, 0.0910],
        [0.4068, 0.4102]])

In [27]:
shape = (2,3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.2404, 0.3633, 0.4843],
        [0.7729, 0.4959, 0.6783]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [28]:
tensor = torch.rand(3,4)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


In [30]:
tensor = torch.ones(4,4)
tensor

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [31]:
tensor[0]

tensor([1., 1., 1., 1.])

In [32]:
print(f"First row: {tensor[0]}")

First row: tensor([1., 1., 1., 1.])


In [33]:
print(f"First Column: {tensor[:,0]}")

First Column: tensor([1., 1., 1., 1.])
