<a href="https://colab.research.google.com/github/thilankam/PyTorch_Tutorials/blob/main/PyTorch_Tensors_Tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Tensors
This tutorial is based on the Tensors. A tensor is a generalization of vectors and matrices and is easily understood as multidimentional array. 
Tensors are a type of data structures used in liner algebra (similar to vectors and matrices). 
We can use to calculate arithmetic operations tensors.

In [ ]:
import torch
torch.__version__
import numpy as np
lst = [10,20,30,40,50,60,70,80]
# creating a numpy array using the list
arr = np.array(lst)
arr 
# checking the data type
arr.dtype

dtype('int64')

Now we will convert from Numpy to Tensor

In [ ]:
tensors = torch.from_numpy(arr)
tensors

tensor([10, 20, 30, 40, 50, 60, 70, 80])

We can do indexing similar to how we do it in numpy.

In [ ]:
tensors[:4]
#tensors[1:3]


tensor([10, 20, 30, 40])

In [ ]:
tensors[2:6]

tensor([30, 40, 50, 60])

In [ ]:
tensors[0]

tensor(10)