<a href="https://colab.research.google.com/github/thilankam/PyTorch_Tutorials/blob/main/Tensors_and_ndarrays.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [17]:
import numpy as np
import torch
arr1d = np.array([1,2,3,4,5])
# 2-D array
arr2d = np.array([[1,2,3],[4,5,6]])

# 3-D array
arr3d = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])

In [ ]:
arr1d[2]
arr2d[1,1]
arr3d[0,1,1]
arr3d[1,1,0]
arr3d[1,0,1]
arr3d[0,1,1]

4

In [ ]:
x = torch.rand(5,3)
print(x[1,1].item())

0.23168140649795532


In [ ]:
# reshaping a tensor
x = torch.rand(4,4)
print(x)
y = x.view(16)

print(y)

tensor([[0.8298, 0.4483, 0.6898, 0.0017],
        [0.0546, 0.4307, 0.5032, 0.9601],
        [0.8921, 0.3677, 0.8962, 0.8396],
        [0.4189, 0.3484, 0.8040, 0.4942]])
tensor([0.8298, 0.4483, 0.6898, 0.0017, 0.0546, 0.4307, 0.5032, 0.9601, 0.8921,
        0.3677, 0.8962, 0.8396, 0.4189, 0.3484, 0.8040, 0.4942])


In [ ]:
# without specifiying the dimention
y = x.view(-1,8)
print(y)
print(y.size())

tensor([[0.8298, 0.4483, 0.6898, 0.0017, 0.0546, 0.4307, 0.5032, 0.9601],
        [0.8921, 0.3677, 0.8962, 0.8396, 0.4189, 0.3484, 0.8040, 0.4942]])
torch.Size([2, 8])


In [ ]:
# converting numpy to torch tensor
a = torch.ones(5)
print(a)

b = a.numpy()
print(b)
print(type(b))

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]
<class 'numpy.ndarray'>


In [ ]:
# if the tensor is on CPU, both tensors wiill share the same memory location
# and if we change one, it will change the other
a.add_(1)
print(a)
print(b)

tensor([3., 3., 3., 3., 3.])
[3. 3. 3. 3. 3.]


In [ ]:


a = np.ones(5)
print(a)
b = torch.from_numpy(a)
print(b)



[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


In [ ]:
a += 1

print(a)

print(b)

[4. 4. 4. 4. 4.]
tensor([4., 4., 4., 4., 4.], dtype=torch.float64)


numpy can only handle the CPU tensors 

In [ ]:

from torch.cuda import is_available
if torch.cuda.is_available():
   device = torch.device("cuda")
   x = torch.ones(5, device = device)
   y = torch.ones(5)
   y = y.to(device)
   z = x + y
   z = z.to("cpu")
   print(z)


`requires_grad= True` will tell pytorch that it will need to calculate the gradients for the tensor later in the optimization step 

In [18]:
x = torch.ones(5, requires_grad= True)
print(x )

tensor([1., 1., 1., 1., 1.], requires_grad=True)


In [23]:
x = torch.randn(3, requires_grad=True)
print(x)
y = x + 2
print(y)

tensor([ 0.3205,  0.7865, -1.1762], requires_grad=True)
tensor([2.3205, 2.7865, 0.8238], grad_fn=<AddBackward0>)


In [32]:
z = y*y*2
#z = z.mean()
print(z)

tensor([10.7693, 15.5288,  1.3573], grad_fn=<MulBackward0>)


In [33]:

# calculate the gradient
v = torch.tensor([0.1, 1.0, 0.001], dtype= torch.float32)
z.backward(v) # dz/dx
print(x.grad)

tensor([1.8564e+00, 2.2292e+01, 6.5903e-03])
