<a href="https://colab.research.google.com/github/thilankam/PyTorch_Tutorials/blob/main/Tensors_and_ndarrays.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import torch
arr1d = np.array([1,2,3,4,5])
# 2-D array
arr2d = np.array([[1,2,3],[4,5,6]])

# 3-D array
arr3d = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])

In [3]:
arr1d[2]
arr2d[1,1]
arr3d[0,1,1]
arr3d[1,1,0]
arr3d[1,0,1]
arr3d[0,1,1]

4

In [8]:
x = torch.rand(5,3)
print(x[1,1].item())

0.23168140649795532


In [13]:
# reshaping a tensor
x = torch.rand(4,4)
print(x)
y = x.view(16)

print(y)

tensor([[0.8298, 0.4483, 0.6898, 0.0017],
        [0.0546, 0.4307, 0.5032, 0.9601],
        [0.8921, 0.3677, 0.8962, 0.8396],
        [0.4189, 0.3484, 0.8040, 0.4942]])
tensor([0.8298, 0.4483, 0.6898, 0.0017, 0.0546, 0.4307, 0.5032, 0.9601, 0.8921,
        0.3677, 0.8962, 0.8396, 0.4189, 0.3484, 0.8040, 0.4942])


In [16]:
# without specifiying the dimention
y = x.view(-1,8)
print(y)
print(y.size())

tensor([[0.8298, 0.4483, 0.6898, 0.0017, 0.0546, 0.4307, 0.5032, 0.9601],
        [0.8921, 0.3677, 0.8962, 0.8396, 0.4189, 0.3484, 0.8040, 0.4942]])
torch.Size([2, 8])


In [27]:
# converting numpy to torch tensor
a = torch.ones(5)
print(a)

b = a.numpy()
print(b)
print(type(b))

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]
<class 'numpy.ndarray'>


In [29]:
# if the tensor is on CPU, both tensors wiill share the same memory location
# and if we change one, it will change the other
a.add_(1)
print(a)
print(b)

tensor([3., 3., 3., 3., 3.])
[3. 3. 3. 3. 3.]


In [43]:


a = np.ones(5)
print(a)
b = torch.from_numpy(a)
print(b)

a =+ 1

print(a)


[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
1
